### ISSUE TITLE
API deprecated

### ISSUE THREAD

**Issue by Surfoo** [ludoo0d0a/geocaching-api#2]
Hello,

This API is deprecated since the 1st of June. Do you plan to update your SDK to the new REST API?

Thanks :)

**Comment by ludoo0d0a** [comment]
Hi,
I just saw the updates a few days ago.
I need to investigate on this point.
I will try to .
But any PR is welcome ;)

**Comment by Surfoo** [comment]
Hello Ludo,

I just pushed a new repository for oauth2: https://github.com/Surfoo/passport-groundspeak
I can login, but I can't request the API, I don't know how to add the bearer in the header... Maybe It's a good starting point for you, because I'm stuck now.. I'm not comfortable enough with javascript... feel free to fork or make a PR :)

**Comment by ludoo0d0a** [comment]
Yesterday, I started new branch rest-api for both projects : 
https://github.com/ludoo0d0a/passport-geocaching/tree/rest-api
https://github.com/ludoo0d0a/geocaching-api/tree/rest-api

I started to add Oauth2 for passport (as you did from what i see 😄  )

And this morning I had a fast overview of the roadmap to migrate api : A lot of breaking changes are expected, but Groundspeak took the right choice in this new version, A lot of semantic mistakes are removed and fixed.

**Comment by ludoo0d0a** [comment]
v2.1.0 is the first version to implement a the new GC API.
Based on swagger file, it can be regenerated.
geocaching-api-demo is a separated project.
